displayName=Sorted Bank
author=gclef
description=Automatically sort bank items client-side by various sort methods without moving the actual items
tags=bank,sort,organize,items
plugins=com.sortedbank.SortedBankPlugin
build=standard
